# Generated by Django 5.2.7 on 2026-01-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opiekun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta'), (3, 'Inna')])),
                ('status', models.IntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Weterynarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.IntegerField(choices=[(1, 'Mezczyzna'), (2, 'Kobieta'), (3, 'Inna')])),
                ('specjalizacja', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='DostepnoscWeterynarza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godz_od', models.TimeField()),
                ('godz_do', models.TimeField()),
                ('weterynarz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.weterynarz')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('gatunek', models.IntegerField(choices=[(1, 'Pies'), (2, 'Kot')])),
                ('plec', models.IntegerField(choices=[(1, 'Samiec'), (2, 'Samica')])),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('opiekun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.opiekun')),
            ],
            options={
                'ordering': ['opiekun__nazwisko', 'gatunek', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Zaplanowana'), (2, 'Otwarta'), (3, 'Zrealizowana'), (4, 'Odwolana'), (5, 'Nieodwolana')], default=1)),
                ('notatka', models.TextField(blank=True)),
                ('weterynarz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.weterynarz')),
                ('zwierze', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.zwierze')),
            ],
            options={
                'ordering': ['data_wizyty'],
            },
        ),
    ]
