# Generated by Django 5.2.7 on 2026-01-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ['termin_wizyty'], 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.RenameField(
            model_name='wizyta',
            old_name='data_wizyty',
            new_name='termin_wizyty',
        ),
    ]
