# Generated by Django 5.2.7 on 2026-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0003_opiekun_user_weterynarz_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ['data_wizyty', 'godzina_wizyty'], 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.RemoveField(
            model_name='opiekun',
            name='status',
        ),
        migrations.RemoveField(
            model_name='weterynarz',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='termin_wizyty',
        ),
        migrations.RemoveField(
            model_name='zwierze',
            name='status',
        ),
        migrations.AddField(
            model_name='wizyta',
            name='data_wizyty',
            field=models.DateField(default='2026-01-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wizyta',
            name='godzina_wizyty',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.IntegerField(choices=[(1, 'Zaplanowana'), (2, 'Zrealizowana'), (3, 'Odwolana')], default=1),
        ),
    ]
