# Generated by Django 5.2.7 on 2026-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0004_alter_wizyta_options_remove_opiekun_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ['data_wizyty', 'godzina_wizyty', 'status'], 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AlterField(
            model_name='opiekun',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')]),
        ),
        migrations.AlterField(
            model_name='weterynarz',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')]),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.IntegerField(choices=[(1, 'Zaplanowana'), (2, 'Zrealizowana'), (3, 'Odwołana')], default=1),
        ),
        migrations.DeleteModel(
            name='GrafikDostepnosci',
        ),
    ]
