# Generated by Django 5.2.7 on 2026-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0005_alter_wizyta_options_alter_opiekun_plec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiekun',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')], default=3),
        ),
        migrations.AlterField(
            model_name='weterynarz',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')], default=3),
        ),
    ]
