# Generated by Django 5.2.7 on 2026-01-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0006_alter_opiekun_plec_alter_weterynarz_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='zwierze',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='przychodnia.zwierze'),
        ),
    ]
